Repository randombit/botan, pull requests merged in 2023-12, with the labels that each got.

#3801 Fix: ASIO Stream handling of close_notify in handshake
  src/lib/tls/asio/asio_async_ops.h
  src/lib/tls/asio/asio_stream.h
  src/tests/test_tls_stream_integration.cpp
  src/tests/unit_asio_stream.cpp
Labels: bug

#3804 Add check to SM2_PrivateKey::check_key() that private key x is in ]0,q-1[
  src/lib/pubkey/sm2/sm2.cpp
Labels: enhancement

#3823 Extend documentation for encryption and signing parameters
  doc/api_ref/pubkey.rst
Labels: documentation

#3826 Mention CMake configuration in docs
  doc/building.rst
  doc/packaging.rst
Labels: documentation

#3828 Update Doxygen landing page
  src/lib/utils/types.h
Labels: documentation

#3838 Build docs in CI and make it fail on warnings or errors
  .github/workflows/ci.yml
  .gitignore
  doc/api_ref/pubkey.rst
  doc/dev_ref/release_process.rst
  readme.rst
  src/configs/sphinx/conf.py
  src/scripts/build_docs.py
  src/scripts/ci/setup_gh_actions.sh
  src/scripts/website.py
Labels: task

#3842 Remove old release news from handbook
  doc/contents.rst
  doc/old_news.rst
Labels: documentation

#3846 FIX: potential non-constant time division in Kyber
  src/lib/pubkey/kyber/kyber_common/kyber.cpp
Labels: bug

#3848 Fix building examples with Ninja
  configure.py
  src/build-data/ninja.in
Labels: build problem

#3839 FIX: flatten boost buffer sequence for TLS
  src/lib/tls/asio/asio_stream.h
Labels: enhancement

#3814 FIX: Access Violation due to stale reference in OCB
  src/lib/modes/aead/ocb/ocb.cpp
  src/tests/test_ocb.cpp
Labels: bug
