Repository randombit/botan, pull requests merged in 2023-11, with the labels that each got.

#3792 FIX: Some minor TLS bugs found along the way
  src/cli/tls_helpers.h
  src/lib/tls/tls13/msg_certificate_13.cpp
Labels: bug

#3791 FIX: ./botan tls_http_server does not compile for --with-boost --disable-modules=asio
  doc/api_ref/tls.rst
  src/cli/tls_http_server.cpp
  src/examples/tls_stream_client.cpp
  src/lib/tls/asio/asio_async_ops.h
  src/lib/tls/asio/asio_compat.h
  src/lib/tls/asio/asio_context.h
  src/lib/tls/asio/asio_error.h
  src/lib/tls/asio/asio_stream.h
  src/lib/tls/asio/info.txt
  src/lib/utils/boost/boost_compat.h
  src/lib/utils/boost/info.txt
  src/tests/test_tls_stream_integration.cpp
  src/tests/unit_asio_stream.cpp
Labels: build problem

#3794 Improve examples by e.g. using create_or_throw() and fix missing include in stream_cipher.cpp
  src/examples/aes.cpp
  src/examples/aes_cbc.cpp
  src/examples/chacha.cpp
  src/examples/cmac.cpp
  src/examples/dl_group.cpp
  src/examples/ecdh.cpp
  src/examples/ecdsa.cpp
  src/examples/entropy.cpp
  src/examples/gmac.cpp
  src/examples/hash.cpp
  src/examples/hybrid_encryption.cpp
  src/examples/kdf.cpp
  src/examples/pkcs11_module.cpp
  src/examples/pkcs11_session.cpp
  src/examples/pkcs11_slot.cpp
  src/examples/pwdhash.cpp
  src/examples/rsa_encrypt.cpp
  src/examples/tls_stream_client.cpp
  src/examples/xmss.cpp
  src/lib/stream/stream_cipher.cpp
Labels: documentation, build problem

#3798 FIX: ninja bogo_shim generates ./botan_bogo_shim
  src/build-data/ninja.in
Labels: build problem

#3795 FIX: Alert handling in ASIO stream and HTTP Server
  src/cli/tls_http_server.cpp
  src/lib/tls/asio/asio_async_ops.h
  src/lib/tls/asio/asio_stream.h
  src/tests/test_tls_stream_integration.cpp
Labels: bug

#3802 Add algorithm specification names to documentation
  doc/api_ref/block_cipher.rst
  doc/api_ref/cipher_modes.rst
  doc/api_ref/hash.rst
  doc/api_ref/kdf.rst
  doc/api_ref/message_auth_codes.rst
  doc/api_ref/pbkdf.rst
  doc/api_ref/stream_ciphers.rst
  src/lib/modes/mode_pad/mode_pad.h
Labels: documentation

#3771 Feature: RawPublicKey authentication in TLS 1.3 (RFC 7250)
  src/cli/tls_client.cpp
  src/cli/tls_helpers.h
  src/cli/tls_server.cpp
  src/lib/tls/credentials_manager.cpp
  src/lib/tls/credentials_manager.h
  src/lib/tls/msg_cert_verify.cpp
  src/lib/tls/msg_client_hello.cpp
  src/lib/tls/tls12/tls_channel_impl_12.h
  src/lib/tls/tls13/msg_certificate_13.cpp
  src/lib/tls/tls13/msg_encrypted_extensions.cpp
  src/lib/tls/tls13/tls_channel_impl_13.cpp
  src/lib/tls/tls13/tls_channel_impl_13.h
  src/lib/tls/tls13/tls_client_impl_13.cpp
  src/lib/tls/tls13/tls_client_impl_13.h
  src/lib/tls/tls13/tls_handshake_layer_13.cpp
  src/lib/tls/tls13/tls_handshake_layer_13.h
  src/lib/tls/tls13/tls_handshake_state_13.h
  src/lib/tls/tls13/tls_server_impl_13.cpp
  src/lib/tls/tls13/tls_server_impl_13.h
  src/lib/tls/tls_callbacks.cpp
  src/lib/tls/tls_callbacks.h
  src/lib/tls/tls_channel.h
  src/lib/tls/tls_channel_impl.h
  src/lib/tls/tls_client.cpp
  src/lib/tls/tls_client.h
  src/lib/tls/tls_extensions.cpp
  src/lib/tls/tls_extensions.h
  src/lib/tls/tls_messages.h
  src/lib/tls/tls_policy.cpp
  src/lib/tls/tls_policy.h
  src/lib/tls/tls_server.cpp
  src/lib/tls/tls_server.h
  src/lib/tls/tls_session.cpp
  src/lib/tls/tls_session.h
  src/lib/tls/tls_text_policy.cpp
  src/tests/data/tls-policy/rfc8448_rawpubkey.txt
  src/tests/data/tls_13_rfc8448/client_raw_public_keypair.pem
  src/tests/data/tls_13_rfc8448/server_raw_public_keypair.pem
  src/tests/data/tls_13_rfc8448/transcripts.vec
  src/tests/test_tls_rfc8448.cpp
  src/tests/test_tls_session_manager.cpp
Labels: enhancement
