Repository randombit/botan, pull requests merged in 2023-05, with the labels that each got.

#3539 FIX: allow custom KEX logic for TLS 1.2 server
  src/lib/tls/tls12/msg_client_kex.cpp
  src/lib/tls/tls12/msg_server_kex.cpp
  src/lib/tls/tls_messages.h
Labels: bug

#3537 Fixes: RFC-compliance of TLS (EtM extension + Supported Point Formats Extension)
  src/lib/tls/tls12/tls_client_impl_12.cpp
  src/lib/tls/tls_ciphersuite.cpp
  src/lib/tls/tls_ciphersuite.h
  src/lib/tls/tls_extensions.cpp
  src/tests/test_tls.cpp
Labels: enhancement

#3538 Fix compile_commands.json
  configure.py
Labels: bug

#3551 Example: Hybrid Encryption w/ RSA+AES/GCM
  src/examples/hybrid_encryption.cpp
Labels: documentation
