Repository randombit/botan, pull requests merged in 2023-10, with the labels that each got.

#3702 Add some minimal API sanity checks for PK_Signer/PK_Verifier
  doc/api_ref/pkcs11.rst
  src/lib/prov/pkcs11/p11_ecdsa.cpp
  src/lib/prov/pkcs11/p11_rsa.cpp
  src/lib/prov/tpm/tpm.cpp
  src/lib/pubkey/dilithium/dilithium_common/dilithium.cpp
  src/lib/pubkey/ecdsa/ecdsa.cpp
  src/lib/pubkey/ecgdsa/ecgdsa.cpp
  src/lib/pubkey/eckcdsa/eckcdsa.cpp
  src/lib/pubkey/ed25519/ed25519_key.cpp
  src/lib/pubkey/gost_3410/gost_3410.cpp
  src/lib/pubkey/sm2/sm2.cpp
  src/lib/pubkey/xmss/xmss_privatekey.cpp
  src/lib/pubkey/xmss/xmss_verification_operation.h
  src/tests/data/pubkey/api_sign.vec
  src/tests/test_pubkey.cpp
Labels: bug

#3766 FIX: asio stream crashes after faulty initialization
  src/lib/tls/asio/asio_async_ops.h
Labels: bug

#3770 Feature: `AsymmetricKey::generate_another()`
  src/lib/prov/pkcs11/p11_ecdh.h
  src/lib/prov/pkcs11/p11_ecdsa.h
  src/lib/prov/pkcs11/p11_rsa.h
  src/lib/prov/tpm/tpm.h
  src/lib/pubkey/curve25519/curve25519.cpp
  src/lib/pubkey/curve25519/curve25519.h
  src/lib/pubkey/dh/dh.cpp
  src/lib/pubkey/dh/dh.h
  src/lib/pubkey/dilithium/dilithium_common/dilithium.cpp
  src/lib/pubkey/dilithium/dilithium_common/dilithium.h
  src/lib/pubkey/dilithium/dilithium_common/dilithium_symmetric_primitives.h
  src/lib/pubkey/dsa/dsa.cpp
  src/lib/pubkey/dsa/dsa.h
  src/lib/pubkey/ecdh/ecdh.cpp
  src/lib/pubkey/ecdh/ecdh.h
  src/lib/pubkey/ecdsa/ecdsa.cpp
  src/lib/pubkey/ecdsa/ecdsa.h
  src/lib/pubkey/ecgdsa/ecgdsa.cpp
  src/lib/pubkey/ecgdsa/ecgdsa.h
  src/lib/pubkey/ecies/ecies.cpp
  src/lib/pubkey/eckcdsa/eckcdsa.cpp
  src/lib/pubkey/eckcdsa/eckcdsa.h
  src/lib/pubkey/ed25519/ed25519.h
  src/lib/pubkey/ed25519/ed25519_key.cpp
  src/lib/pubkey/elgamal/elgamal.cpp
  src/lib/pubkey/elgamal/elgamal.h
  src/lib/pubkey/gost_3410/gost_3410.cpp
  src/lib/pubkey/gost_3410/gost_3410.h
  src/lib/pubkey/kyber/kyber_common/kyber.cpp
  src/lib/pubkey/kyber/kyber_common/kyber.h
  src/lib/pubkey/mce/mceliece.h
  src/lib/pubkey/mce/mceliece_key.cpp
  src/lib/pubkey/pk_keys.h
  src/lib/pubkey/rsa/rsa.cpp
  src/lib/pubkey/rsa/rsa.h
  src/lib/pubkey/sm2/sm2.cpp
  src/lib/pubkey/sm2/sm2.h
  src/lib/pubkey/sphincsplus/sphincsplus_common/sphincsplus.cpp
  src/lib/pubkey/sphincsplus/sphincsplus_common/sphincsplus.h
  src/lib/pubkey/xmss/xmss.h
  src/lib/pubkey/xmss/xmss_publickey.cpp
  src/lib/tls/tls13_pqc/hybrid_public_key.cpp
  src/lib/tls/tls13_pqc/hybrid_public_key.h
  src/lib/tls/tls13_pqc/kex_to_kem_adapter.cpp
  src/lib/tls/tls13_pqc/kex_to_kem_adapter.h
  src/tests/test_pubkey.cpp
Labels: enhancement

#3765 Introduce <botan/boost_compat.h> as feature flag
  doc/api_ref/tls.rst
  src/examples/tls_stream_client.cpp
  src/lib/tls/asio/asio_async_ops.h
  src/lib/tls/asio/asio_context.h
  src/lib/tls/asio/asio_error.h
  src/lib/tls/asio/asio_stream.h
  src/lib/utils/boost/boost_compat.h
  src/lib/utils/boost/info.txt
  src/tests/test_tls_stream_integration.cpp
  src/tests/unit_asio_stream.cpp
Labels: enhancement

#3782 Add EC_PrivateKey::check_key() to check private value of EC keys (#3648)
  src/lib/pubkey/ecc_key/ecc_key.cpp
  src/lib/pubkey/ecc_key/ecc_key.h
  src/lib/pubkey/ecdsa/ecdsa.cpp
  src/lib/pubkey/ecgdsa/ecgdsa.cpp
  src/lib/pubkey/eckcdsa/eckcdsa.cpp
  src/lib/pubkey/sm2/sm2.cpp
Labels: bug, enhancement
