Repository randombit/botan, pull requests merged in 2024-11, with the labels that each got.

#4421 Nightly Valgrind Matrix
  .github/workflows/nightly.yml
  src/ct_selftest/ct_selftest.py
  src/lib/math/bigint/bigint.cpp
  src/scripts/ci/setup_gh_actions.sh
  src/scripts/ci_build.py
Labels: infra

#4422 Chore: Centralize some Repository Config
  .github/actions/read-repo-config/action.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/nightly.yml
  doc/dev_ref/continuous_integration.rst
  src/configs/repo_config.env
  src/scripts/ci/setup_gh_actions.ps1
  src/scripts/ci/setup_gh_actions.sh
  src/scripts/ci_build.py
  src/scripts/repo_config.py
Labels: infra

#4423 FIX: sde utility not in $PATH
  src/scripts/ci/setup_gh_actions.sh
Labels: infra

#4427 FIX: typo in Jitter RNG documentation
  doc/api_ref/rng.rst
Labels: documentation

#4430 Feature: Support external ESYS_CONTEXT in TPM2
  doc/api_ref/ffi.rst
  doc/api_ref/tpm.rst
  src/lib/ffi/ffi.h
  src/lib/ffi/ffi_tpm2.cpp
  src/lib/prov/tpm2/tpm2_context.cpp
  src/lib/prov/tpm2/tpm2_context.h
  src/lib/prov/tpm2/tpm2_crypto_backend/info.txt
  src/lib/prov/tpm2/tpm2_crypto_backend/tpm2_crypto_backend.cpp
  src/lib/prov/tpm2/tpm2_crypto_backend/tpm2_crypto_backend.h
  src/lib/prov/tpm2/tpm2_crypto_backend/tpm2_crypto_backend_impl.cpp
  src/lib/prov/tpm2/tpm2_crypto_backend/tpm2_crypto_backend_impl.h
  src/tests/test_ffi.cpp
  src/tests/test_tpm2.cpp
Labels: enhancement

#4437 Split loading and generating ECC private key c'tors
  src/examples/ecc_raw_private_key.cpp
  src/lib/pubkey/ecc_key/ec_key_data.cpp
  src/lib/pubkey/ecc_key/ec_key_data.h
  src/lib/pubkey/ecc_key/ecc_key.cpp
  src/lib/pubkey/ecc_key/ecc_key.h
  src/lib/pubkey/ecdh/ecdh.h
  src/lib/pubkey/ecdsa/ecdsa.h
  src/lib/pubkey/ecgdsa/ecgdsa.h
  src/lib/pubkey/eckcdsa/eckcdsa.h
  src/lib/pubkey/gost_3410/gost_3410.cpp
  src/lib/pubkey/gost_3410/gost_3410.h
  src/lib/pubkey/sm2/sm2.cpp
  src/lib/pubkey/sm2/sm2.h
Labels: enhancement
