Repository randombit/botan, pull requests merged in 2024-10, with the labels that each got.

#4350 Use @response_files.txt for linking in Ninja
  configure.py
  src/build-data/ninja.in
Labels: build problem

#4337 Feature: TPM2 Support
  .github/actions/setup-build-agent/action.yml
  .github/workflows/ci.yml
  configure.py
  doc/api_ref/providers.rst
  doc/api_ref/rng.rst
  doc/api_ref/tpm.rst
  doc/building.rst
  doc/dev_ref/contributing.rst
  doc/dev_ref/todo.rst
  readme.rst
  src/cli/argparse.h
  src/examples/pkcs10_csr_on_tpm2.cpp
  src/lib/prov/tpm2/info.txt
  src/lib/prov/tpm2/tpm2_algo_mappings.h
  src/lib/prov/tpm2/tpm2_context.cpp
  src/lib/prov/tpm2/tpm2_context.h
  src/lib/prov/tpm2/tpm2_crypto_backend/info.txt
  src/lib/prov/tpm2/tpm2_crypto_backend/tpm2_crypto_backend.cpp
  src/lib/prov/tpm2/tpm2_crypto_backend/tpm2_crypto_backend.h
  src/lib/prov/tpm2/tpm2_error.cpp
  src/lib/prov/tpm2/tpm2_error.h
  src/lib/prov/tpm2/tpm2_hash.cpp
  src/lib/prov/tpm2/tpm2_hash.h
  src/lib/prov/tpm2/tpm2_key.cpp
  src/lib/prov/tpm2/tpm2_key.h
  src/lib/prov/tpm2/tpm2_object.cpp
  src/lib/prov/tpm2/tpm2_object.h
  src/lib/prov/tpm2/tpm2_rng.cpp
  src/lib/prov/tpm2/tpm2_rng.h
  src/lib/prov/tpm2/tpm2_rsa/info.txt
  src/lib/prov/tpm2/tpm2_rsa/tpm2_rsa.cpp
  src/lib/prov/tpm2/tpm2_rsa/tpm2_rsa.h
  src/lib/prov/tpm2/tpm2_session.cpp
  src/lib/prov/tpm2/tpm2_session.h
  src/lib/prov/tpm2/tpm2_util.h
  src/lib/utils/stl_util.h
  src/scripts/ci/setup_gh_actions.sh
  src/scripts/ci/start_tpm2_simulator.sh
  src/scripts/ci_build.py
  src/tests/main.cpp
  src/tests/test_tpm2.cpp
  src/tests/tests.h
Labels: enhancement

#4357 Feature: ECC Support in TPM2
  doc/api_ref/tpm.rst
  src/lib/prov/tpm2/info.txt
  src/lib/prov/tpm2/tpm2_algo_mappings.h
  src/lib/prov/tpm2/tpm2_context.cpp
  src/lib/prov/tpm2/tpm2_context.h
  src/lib/prov/tpm2/tpm2_crypto_backend/tpm2_crypto_backend.cpp
  src/lib/prov/tpm2/tpm2_crypto_backend/tpm2_crypto_backend.h
  src/lib/prov/tpm2/tpm2_ecc/info.txt
  src/lib/prov/tpm2/tpm2_ecc/tpm2_ecc.cpp
  src/lib/prov/tpm2/tpm2_ecc/tpm2_ecc.h
  src/lib/prov/tpm2/tpm2_error.cpp
  src/lib/prov/tpm2/tpm2_error.h
  src/lib/prov/tpm2/tpm2_hash.cpp
  src/lib/prov/tpm2/tpm2_hash.h
  src/lib/prov/tpm2/tpm2_key.cpp
  src/lib/prov/tpm2/tpm2_key.h
  src/lib/prov/tpm2/tpm2_object.cpp
  src/lib/prov/tpm2/tpm2_object.h
  src/lib/prov/tpm2/tpm2_pkops.cpp
  src/lib/prov/tpm2/tpm2_pkops.h
  src/lib/prov/tpm2/tpm2_rng.cpp
  src/lib/prov/tpm2/tpm2_rng.h
  src/lib/prov/tpm2/tpm2_rsa/tpm2_rsa.cpp
  src/lib/prov/tpm2/tpm2_rsa/tpm2_rsa.h
  src/lib/prov/tpm2/tpm2_session.cpp
  src/lib/prov/tpm2/tpm2_session.h
  src/lib/prov/tpm2/tpm2_util.h
  src/lib/pubkey/ec_group/ec_group.h
  src/scripts/ci/start_tpm2_simulator.sh
  src/scripts/ci_build.py
  src/tests/test_tpm2.cpp
Labels: enhancement

#4361 TPM2: Basic bindings in FFI & Python
  doc/api_ref/ffi.rst
  doc/api_ref/python.rst
  src/lib/ffi/ffi.cpp
  src/lib/ffi/ffi.h
  src/lib/ffi/ffi_tpm2.cpp
  src/python/botan3.py
  src/scripts/ci_build.py
  src/scripts/test_python.py
  src/tests/test_ffi.cpp
Labels: enhancement

#4368 FFI/Python: Expose raw public/private key encoding functions
  doc/api_ref/ffi.rst
  doc/api_ref/python.rst
  src/lib/ffi/ffi.h
  src/lib/ffi/ffi_pkey.cpp
  src/python/botan3.py
  src/scripts/test_python.py
  src/tests/test_ffi.cpp
Labels: enhancement

#4373 FFI: Loading of raw FrodoKEM keys & FIX: "insufficient buffer handling" in FFI's decapsulate
  src/lib/ffi/ffi.h
  src/lib/ffi/ffi_pk_op.cpp
  src/lib/ffi/ffi_pkey_algs.cpp
  src/lib/pubkey/frodokem/frodokem_common/frodo_constants.cpp
  src/python/botan3.py
  src/scripts/test_python.py
  src/tests/test_ffi.cpp
Labels: bug, enhancement

#3893 PQC: ML-KEM
  doc/api_ref/pubkey.rst
  doc/api_ref/python.rst
  doc/index.rst
  readme.rst
  src/build-data/oids.txt
  src/cli/perf_pk_kem.cpp
  src/cli/speed.cpp
  src/examples/hybrid_key_encapsulation.cpp
  src/examples/ml_kem.cpp
  src/lib/asn1/oid_maps.cpp
  src/lib/ffi/ffi.h
  src/lib/ffi/ffi_pkey_algs.cpp
  src/lib/pubkey/kyber/kyber_common/kyber.cpp
  src/lib/pubkey/kyber/kyber_common/kyber.h
  src/lib/pubkey/kyber/kyber_common/kyber_algos.cpp
  src/lib/pubkey/kyber/kyber_common/kyber_algos.h
  src/lib/pubkey/kyber/kyber_common/kyber_constants.cpp
  src/lib/pubkey/kyber/kyber_common/kyber_constants.h
  src/lib/pubkey/kyber/kyber_common/kyber_helpers.h
  src/lib/pubkey/kyber/kyber_common/kyber_keys.cpp
  src/lib/pubkey/kyber/kyber_common/kyber_keys.h
  src/lib/pubkey/kyber/kyber_common/kyber_polynomial.h
  src/lib/pubkey/kyber/kyber_common/kyber_symmetric_primitives.h
  src/lib/pubkey/kyber/kyber_common/kyber_types.h
  src/lib/pubkey/kyber/kyber_round3/info.txt
  src/lib/pubkey/kyber/kyber_round3/kyber/kyber_modern.h
  src/lib/pubkey/kyber/kyber_round3/kyber_90s/kyber_90s.h
  src/lib/pubkey/kyber/kyber_round3/kyber_encaps.cpp
  src/lib/pubkey/kyber/kyber_round3/kyber_round3_impl.cpp
  src/lib/pubkey/kyber/kyber_round3/kyber_round3_impl.h
  src/lib/pubkey/kyber/ml_kem/info.txt
  src/lib/pubkey/kyber/ml_kem/ml_kem_impl.cpp
  src/lib/pubkey/kyber/ml_kem/ml_kem_impl.h
  src/lib/pubkey/pk_algs.cpp
  src/lib/pubkey/pqcrystals/pqcrystals_encoding.h
  src/lib/pubkey/pqcrystals/pqcrystals_helpers.h
  src/lib/utils/ct_utils.h
  src/lib/utils/types.h
  src/python/botan3.py
  src/scripts/dev_tools/gen_kyber_kat.py
  src/scripts/dev_tools/gen_mlkem_acvp_kat.py
  src/scripts/test_python.py
  src/tests/data/pubkey/kyber_encodings.vec
  src/tests/data/pubkey/ml_kem.vec
  src/tests/data/pubkey/ml_kem_acvp_encap.vec
  src/tests/data/pubkey/ml_kem_acvp_keygen.vec
  src/tests/test_crystals.cpp
  src/tests/test_ffi.cpp
  src/tests/test_kyber.cpp
  src/tests/test_pubkey.cpp
  src/tests/test_pubkey.h
  src/tests/test_pubkey_pqc.h
  src/tests/unit_x509.cpp
Labels: enhancement

#4384 Refactor: Centralize X25519/X448 all-zero result rejection
  src/lib/pubkey/curve448/x448/x448.cpp
  src/lib/pubkey/x25519/x25519.cpp
  src/lib/tls/tls12/msg_client_kex.cpp
  src/lib/tls/tls13/tls_extensions_key_share.cpp
  src/lib/tls/tls_callbacks.cpp
  src/tests/test_pubkey.cpp
  src/tests/test_pubkey.h
  src/tests/test_x25519.cpp
  src/tests/test_x448.cpp
Labels: bug

#4389 TLS: BoGo tests update
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  doc/api_ref/tls.rst
  src/bogo_shim/bogo_shim.cpp
  src/bogo_shim/config.json
  src/editors/vscode/scripts/bogo.py
  src/examples/tls_custom_curves_client.cpp
  src/lib/tls/msg_cert_verify.cpp
  src/lib/tls/tls12/msg_client_kex.cpp
  src/lib/tls/tls12/tls_handshake_state.cpp
  src/lib/tls/tls13_pqc/hybrid_public_key.cpp
  src/lib/tls/tls_callbacks.cpp
  src/lib/tls/tls_callbacks.h
Labels: enhancement

#4391 FIX: Assertion may be false for untrusted data
  src/lib/pubkey/pqcrystals/pqcrystals_encoding.h
  src/tests/data/pubkey/kyber_encodings.vec
Labels: bug

#4398 FIX: SLH-DSA should default to 'Hedged' variant
  src/lib/pubkey/sphincsplus/sphincsplus_common/sphincsplus.cpp
  src/tests/data/pubkey/slh_dsa_generic.vec
  src/tests/test_sphincsplus.cpp
Labels: bug
