Repository randombit/botan, pull requests merged in 2024-03, with the labels that each got.

#3932 FIX: Emscripten build on macOS
  .github/workflows/ci.yml
  src/build-data/detect_version.cpp
Labels: build problem

#3935 Doc: Example to encrypt a message using a password
  doc/api_ref/pbkdf.rst
  src/examples/password_encryption.cpp
Labels: documentation

#3931 FIX: arm64 amalgamations + better CI coverage
  .github/workflows/ci.yml
  src/lib/block/aes/aes_armv8/aes_armv8.cpp
  src/lib/block/shacal2/shacal2_armv8/shacal2_arvm8.cpp
  src/lib/block/sm4/sm4_armv8/sm4_armv8.cpp
  src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp
  src/lib/hash/sha2_32/sha2_32_armv8/sha2_32_armv8.cpp
  src/lib/hash/sha2_64/sha2_64_armv8/sha2_64_armv8.cpp
  src/lib/utils/simd/simd_32.h
  src/python/botan3.py
  src/scripts/ci/setup_gh_actions.sh
  src/scripts/ci_build.py
  src/scripts/test_cli.py
Labels: build problem

#3938 X509 Path Validation Flag to Ignore Root Certificate Lifetime
  src/lib/x509/cert_status.cpp
  src/lib/x509/pkix_enums.h
  src/lib/x509/x509path.cpp
  src/lib/x509/x509path.h
  src/tests/data/x509/misc/root_cert_time_check/README.md
  src/tests/data/x509/misc/root_cert_time_check/leaf.crt
  src/tests/data/x509/misc/root_cert_time_check/root.crt
  src/tests/test_x509_path.cpp
Labels: enhancement

#3910 Feature: Module Lifecycle and Experimental/Deprecated Features
  configure.py
  doc/building.rst
  doc/dev_ref/configure.rst
  doc/sem_ver.rst
  src/build-data/buildh.in
  src/build-data/module_info.in
  src/scripts/ci_build.py
Labels: enhancement

#3885 Chore: Modernize copy_out_be/le
  src/lib/block/aes/aes.cpp
  src/lib/compat/sodium/sodium_salsa.cpp
  src/lib/hash/blake2/blake2b.cpp
  src/lib/hash/blake2s/blake2s.cpp
  src/lib/hash/mdx_hash/mdx_hash.h
  src/lib/hash/skein/skein_512.cpp
  src/lib/utils/loadstor.h
  src/lib/utils/poly_dbl/poly_dbl.cpp
  src/tests/test_utils.cpp
Labels: enhancement

#3944 FIX: wrong module name for AES ARM acceleration
  doc/hardware_acceleration.rst
Labels: documentation
