Repository randombit/botan, pull requests merged in 2024-01, with the labels that each got.

#3868 Fix typo in PKCS#11 hash function mapping
  src/lib/prov/pkcs11/p11_rsa.cpp
Labels: bug

#3679 PQC: FrodoKEM
  doc/api_ref/pubkey.rst
  doc/dev_ref/oids.rst
  src/build-data/oids.txt
  src/cli/speed.cpp
  src/lib/asn1/oid_maps.cpp
  src/lib/pubkey/frodokem/frodokem/frodo_shake_generator.h
  src/lib/pubkey/frodokem/frodokem/info.txt
  src/lib/pubkey/frodokem/frodokem_aes/frodo_aes_generator.h
  src/lib/pubkey/frodokem/frodokem_aes/info.txt
  src/lib/pubkey/frodokem/frodokem_common/frodo_constants.cpp
  src/lib/pubkey/frodokem/frodokem_common/frodo_constants.h
  src/lib/pubkey/frodokem/frodokem_common/frodo_matrix.cpp
  src/lib/pubkey/frodokem/frodokem_common/frodo_matrix.h
  src/lib/pubkey/frodokem/frodokem_common/frodo_mode.cpp
  src/lib/pubkey/frodokem/frodokem_common/frodo_mode.h
  src/lib/pubkey/frodokem/frodokem_common/frodo_types.h
  src/lib/pubkey/frodokem/frodokem_common/frodokem.cpp
  src/lib/pubkey/frodokem/frodokem_common/frodokem.h
  src/lib/pubkey/frodokem/frodokem_common/info.txt
  src/lib/pubkey/pk_algs.cpp
  src/lib/tls/tls13_pqc/hybrid_public_key.cpp
  src/lib/tls/tls_algos.cpp
  src/lib/tls/tls_algos.h
  src/lib/tls/tls_callbacks.cpp
  src/lib/utils/strong_type.h
  src/scripts/dev_tools/gen_frodo_kat.py
  src/scripts/test_cli.py
  src/tests/data/pubkey/frodokem_kat.vec
  src/tests/test_frodokem.cpp
  src/tests/unit_x509.cpp
Labels: enhancement

#3875 [Botan 2.x] FIX: install GCC 4.8 from deb packages at kernel.org
  .github/workflows/ci.yml
  src/scripts/ci/setup_gh_actions.sh
Labels: build problem

#3845 Fix CLI tests under windows and enabled them in the CI
  src/cli/cli.cpp
  src/cli/cli.h
  src/cli/cli_rng.cpp
  src/cli/codec.cpp
  src/cli/pk_crypt.cpp
  src/cli/tss.cpp
  src/cli/zfec.cpp
  src/lib/utils/os_utils.cpp
  src/scripts/ci_build.py
  src/scripts/test_cli.py
Labels: bug

#3888 CI: Update GitHub Actions Ubuntu workaround
  src/scripts/ci/setup_gh_actions.sh
Labels: build problem
